- name: Ensure machine is started
  hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/vars/configuration.yml"
  tasks:
    - name: Start vm
      community.proxmox.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ vmid }}"
        state: started

- name: setup FortiGate
  hosts: ftg
  connection: httpapi
  gather_facts: false
  collections:
    - fortinet.fortios
  vars_files:
    - "{{ playbook_dir }}/vars/configuration.yml"
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 8006
  roles:
    - "interfaces-auto-setup"

