fortigate_token: "{{ lookup('ansible.builtin.env', 'FORTIGATE_TOKEN') }}"
fortigate_host: "{{ lookup('ansible.builtin.env', 'FORTIGATE_IP') }}"
fortigate_username: "{{ lookup('ansible.builtin.env', 'FORTIGATE_USR') }}"
fortigate_password: "{{ lookup('ansible.builtin.env', 'FORTIGATE_PWD') }}"

vdom: root
psk_secret: "{{ lookup('ansible.builtin.env', 'FORTIGATE_VPN_SECRET') }}"
client_fqdn: "trusted.fortilab.tdz.ovh"
fg_fqdn: "core-fortigate.fortilab.tdz.ovh"
vpn_pool_name: "remote-access-ip-pool"
vpn_pool_start: "10.0.3.100"
vpn_pool_end: "10.0.3.150"
vpn_pool_mask: "255.255.255.0"
phase1_name: "remote-access"
phase2_name: "remote-access-phase-2"
