- name: Deploy with color output enabled
  community.general.terraform:
    project_path: '{{ project_dir }}' # got from the playbook which call the role
    state: present
    no_color: false
    complex_vars: true
    variables:
      vms: vm_list


