- name: Deploy tinyproxy lxc
  hosts: localhost
  vars:
    dir: "{{ project_dir }}"
  tasks:
    - name: terraform deploy
      community.general.terraform:
        project_path: "{{ dir }}"
        state: present
        complex_vars: true
        variables:
          lxc:
            - name: "dmz-proxy"
              id: 505
              ram: 1024
              cores: 1
              os: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
              pool: "dmz"
              root_disk:
                - size: "5G"
                  storage: vm_storage
              network:
                - name: "eth0"
                  bridge: "dmz.20"
                  ipv4: "10.0.2.50"
