- name: Deploy fortigate virtual machine
  hosts: localhost
  vars:
    dir: "{{ project_dir }}"
  tasks:
    - name: terraform deploy
      community.general.terraform:
        project_path: "{{ dir }}"
        state: present
        complex_vars: true
        variables:
          vms:
            - name: core-firewall
              id: "{{ gate_id }}"
              ram: 4096
              cores: 4
              sockets: 1
              os: ""
              pool: tdz-dmz
              vm_state: "stopped"
              disks:
                - size: 10G
                  storage: "{{ vm_storage }}"
                  slot: "scsi1"
              network:
                - id: 0
                  name: "eth0"
                  bridge: "vmbr0"
                  macaddr: 02:00:00:8b:21:ea
                - id: 1
                  name: eth1
                  bridge: dmz
                  macaddr: ""

- name: load disk to proxmox
  hosts: proxmox
  tasks:
    - name: copy disk to proxmox
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../files/fortigate-v4.6.6.qcow2"
        dest: "/tmp/fortigate.qcow2"
    - name: attach disk to fortigate
      command: "qm importdisk {{ gate_id }} /tmp/fortigate.qcow2 local --target-disk scsi0"
