- name: Deploy k3s cluster lxc
  hosts: localhost
  vars:
    dir: "{{ project_dir }}"
  tasks:
    - name: terraform deploy
      community.general.terraform:
        project_path: "{{ dir }}"
        state: present
        complex_vars: true
        variables:
          lxc:
            - name: "lan-k3s-load-balancer"
              id: 502
              ram: 1024
              cores: 1
              os: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
              pool: "tdz-lan"
              root_disk:
                - size: "5G"
                  storage: "{{ vm_storage }}"
              network:
                - name: "eth0"
                  bridge: "lan.10"
                  ipv4: "10.1.1.49/24"

            - name: "lan-k3s-server-00"
              id: 503
              ram: 2048
              cores: 2
              os: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
              pool: "tdz-lan"
              root_disk:
                - size: "5G"
                  storage: "{{ vm_storage }}"
              network:
                - name: "eth0"
                  bridge: "lan.10"
                  ipv4: "10.1.1.50/24"

            - name: "lan-k3s-server-01"
              id: 504
              ram: 2048
              cores: 2
              os: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
              pool: "tdz-lan"
              root_disk:
                - size: "5G"
                  storage: "{{ vm_storage }}"
              network:
                - name: "eth0"
                  bridge: "lan.10"
                  ipv4: "10.1.1.51/24"

            - name: "lan-k3s-00"
              id: 505
              ram: 1024
              cores: 1
              os: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
              pool: "tdz-lan"
              root_disk:
                - size: "5G"
                  storage: "{{ vm_storage }}"
              network:
                - name: "eth0"
                  bridge: "lan.10"
                  ipv4: "10.1.1.60/24"

            - name: "lan-k3s-01"
              id: 506
              ram: 1024
              cores: 1
              os: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
              pool: "tdz-lan"
              root_disk:
                - size: "5G"
                  storage: "{{ vm_storage }}"
              network:
                - name: "eth0"
                  bridge: "lan.10"
                  ipv4: "10.1.1.61/24"

            - name: "lan-k3s-02"
              id: 507
              ram: 1024
              cores: 1
              os: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
              pool: "tdz-lan"
              root_disk:
                - size: "5G"
                  storage: "{{ vm_storage }}"
              network:
                - name: "eth0"
                  bridge: "lan.10"
                  ipv4: "10.1.1.62/24"