---
- name: Setup reverse-proxy
  hosts: debian
  become: true
  vars:
    target_user: zhou
    target_home: "/home/{{ target_user }}"

  tasks:
    - name: Proxy
      include_tasks: tasks/proxy.yml

    - name: Base Debian
      include_tasks: tasks/quick_debian.yml

    - name: Docker
      include_tasks: tasks/docker.yml

    - name: Create traefik directories
      ansible.builtin.file:
        path: "/opt/containers/traefik/letsencrypt"
        state: directory
        mode: "0755"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Download custom compose.yml
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/zhou-efr/tdzhouse/master/ansible/config/traefik/compose.yml
        dest: "/opt/containers/traefik/compose.yml"
        mode: "0644"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Download custom dynamic.yml
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/zhou-efr/tdzhouse/master/ansible/config/traefik/dynamic.yml
        dest: "/opt/containers/traefik/dynamic.yml"
        mode: "0644"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Download custom traefik.yml
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/zhou-efr/tdzhouse/master/ansible/config/traefik/traefik.yml
        dest: "/opt/containers/traefik/traefik.yml"
        mode: "0644"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Deploy traefik stack
      become: true
      community.docker.docker_compose_v2:
        project_src: /opt/containers/traefik
        files:
          - compose.yml
        state: present

- name: Setup proxy
  hosts: all
  become: true
  vars:
    tinyproxy_src_dir: /opt/tinyproxy
    tinyproxy_conf_dir: /etc/tinyproxy
    tinyproxy_conf_file: /etc/tinyproxy/tinyproxy.conf
    tinyproxy_log_dir: /var/log/tinyproxy
    tinyproxy_log_file: /var/log/tinyproxy/default.conf.log

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - build-essential
          - git
          - wget
          - autoconf
          - automake
          - libtool
        state: present
        update_cache: true

    - name: Clone tinyproxy
      ansible.builtin.git:
        repo: https://github.com/tinyproxy/tinyproxy.git
        dest: "{{ tinyproxy_src_dir }}"
        version: master

    - name: Tinyproxy autogen
      ansible.builtin.command:
        cmd: ./autogen.sh
        chdir: "{{ tinyproxy_src_dir }}"
      args:
        creates: "{{ tinyproxy_src_dir }}/configure"

    - name: Tinyproxy configuration
      ansible.builtin.command:
        cmd: ./configure --enable-filter
        chdir: "{{ tinyproxy_src_dir }}"
      args:
        creates: "{{ tinyproxy_src_dir }}/Makefile"

    - name: Compile tinyproxy
      ansible.builtin.command:
        cmd: make
        chdir: "{{ tinyproxy_src_dir }}"
      args:
        creates: "{{ tinyproxy_src_dir }}/src/tinyproxy"

    - name: Install tinyproxy
      ansible.builtin.command:
        cmd: make install
        chdir: "{{ tinyproxy_src_dir }}"
      args:
        creates: /usr/local/bin/tinyproxy

    - name: Create configuration directory
      ansible.builtin.file:
        path: "{{ tinyproxy_conf_dir }}"
        state: directory
        mode: "0755"

    - name: Download tinyproxy configuration
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/zhou-efr/tdzhouse/master/ansible/config/tinyproxy/tinyproxy.yml
        dest: "{{ tinyproxy_conf_file }}"
        mode: "0766"

    - name: Create log directory
      ansible.builtin.file:
        path: "{{ tinyproxy_log_dir }}"
        state: directory
        mode: "0755"

    - name: Create log file
      ansible.builtin.file:
        path: "{{ tinyproxy_log_file }}"
        state: touch
        mode: "0766"

    - name: Start tinyproxy
      ansible.builtin.shell: |
        nohup /usr/local/bin/tinyproxy -d -c {{ tinyproxy_conf_file }} >/var/log/tinyproxy/startup.log 2>&1 &
      args:
        creates: /var/log/tinyproxy/startup.log
