---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'

  children:
    debian:
      hosts:
        dmz-reverse-proxy:
          ansible_host: 10.0.1.50
        dmz-proxy:
          ansible_host: 10.0.2.50
        proxmox:
          ansible_host: 152.228.227.39
        lan-docker:
          ansible_host: 10.1.1.50

    firewall:
      hosts:
        core-fortigate:
          ansible_host: "{{ lookup('ansible.builtin.env', 'FORTIGATE_IP') }}"