- name: Env var loading validation
  ansible.builtin.debug:
    msg: "{{ ansible_httpapi_host }}"

- name: Interface wan
  fortinet.fortios.fortios_system_interface:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    system_interface:
      name: "port1"
      alias: "wan"

- name: Interface dmz
  fortinet.fortios.fortios_system_interface:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    system_interface:
      name: "port2"
      alias: "dmz"

- name: Interface lan
  fortinet.fortios.fortios_system_interface:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    system_interface:
      name: "port3"
      alias: "lan"

- name: Ajouter vlan dmz in
  fortinet.fortios.fortios_system_interface:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    system_interface:
      name: "dmz-in"
      type: "vlan"
      vlanid: 10
      interface: "internal"
      mode: "static"
      ip: "10.0.1.0 255.255.255.0"

- name: Ajouter vlan dmz out
  fortinet.fortios.fortios_system_interface:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    system_interface:
      name: "dmz-out"
      type: "vlan"
      vlanid: 20
      interface: "internal"
      mode: "static"
      ip: "10.0.2.0 255.255.255.0"

- name: Ajouter vlan lan web
  fortinet.fortios.fortios_system_interface:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    system_interface:
      name: "lan-web"
      type: "vlan"
      vlanid: 10
      interface: "internal"
      mode: "static"
      ip: "10.1.1.0 255.255.255.0"

- name: Alias reverse-proxy
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "reverse-proxy"
      type: "ipmask"
      subnet: "10.0.1.50 255.255.255.255"

- name: Alias proxy
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "proxy"
      type: "ipmask"
      subnet: "10.0.2.50 255.255.255.255"

- name: Alias ingress k3s
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "k3s-ingress"
      type: "ipmask"
      subnet: "10.1.1.50 255.255.255.255"

- name: Alias server k3s 00
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "k3s-server-00"
      type: "ipmask"
      subnet: "10.1.1.60 255.255.255.255"

- name: Alias server k3s 01
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "k3s-server-01"
      type: "ipmask"
      subnet: "10.1.1.61 255.255.255.255"

- name: Alias node k3s 00
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "k3s-node-00"
      type: "ipmask"
      subnet: "10.1.1.70 255.255.255.255"

- name: Alias node k3s 01
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "k3s-node-01"
      type: "ipmask"
      subnet: "10.1.1.71 255.255.255.255"

- name: Alias node k3s 02
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "k3s-node-02"
      type: "ipmask"
      subnet: "10.1.1.72 255.255.255.255"

- name: Groupe node k3s
  fortinet.fortios.fortios_firewall_addrgrp:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_addrgrp:
      name: "k3s-nodes"
      member:
        - name: "k3s-node-00"
        - name: "k3s-node-01"
        - name: "k3s-node-02"

- name: Groupe servers k3s
  fortinet.fortios.fortios_firewall_addrgrp:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_addrgrp:
      name: "k3s-servers"
      member:
        - name: "k3s-server-00"
        - name: "k3s-server-01"

- name: Alias l'appart
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "l-appart"
      type: "ipmask"
      subnet: "176.187.69.6 255.255.255.255"

- name: Alias tour alto
  fortinet.fortios.fortios_firewall_address:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_address:
      name: "tour-alto"
      type: "ipmask"
      subnet: "84.14.248.10 255.255.255.255"

- name: Groupe trusted hosts
  fortinet.fortios.fortios_firewall_addrgrp:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_addrgrp:
      name: "trusted-hosts"
      member:
        - name: "l-appart"
        - name: "tour-alto"

- name: Policy proxy to internet
  fortios_firewall_policy:
    vdom: "root"
    state: "present"
    access_token: "{{ fortigate_token }}"
    firewall_policy:
      name: "proxy to internet"
      srcintf:
        - name: "dmz-out"
      dstintf:
        - name: "wan"
      srcaddr:
        - name: "proxy"
      dstaddr:
        - name: "ALL"
      service:
        - name: "HTTP"
        - name: "HTTPS"
        - name: "FTP"
      schedule: "always"
      action: "accept"
      nat: "enable"
      logtraffic: "all"
