- name: Configure persistent proxy settings in /etc/environment
  ansible.builtin.blockinfile:
    path: /etc/environment
    create: true
    marker: "# {mark} ANSIBLE MANAGED PROXY SETTINGS"
    block: |
      http_proxy={{ proxy_url }}
      https_proxy={{ proxy_url }}
      ftp_proxy={{ proxy_url }}
      no_proxy={{ no_proxy_list }}

- name: Configure apt proxy
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/95proxies
    mode: "0644"
    content: |
      Acquire::http::Proxy "{{ proxy_url }}";
      Acquire::https::Proxy "{{ proxy_url }}";

- name: Reboot machine to apply changes
  ansible.builtin.reboot:
    reboot_timeout: 30 # peut-être à adapter en fonction du temps de redémarrage des lxc
    test_command: whoami
