proxmox_host: "{{ lookup('ansible.builtin.env', 'PROXMOX_HOST') }}"
proxmox_user: "{{ lookup('ansible.builtin.env', 'PROXMOX_USER') }}"
proxmox_token_id: "{{ lookup('ansible.builtin.env', 'PROXMOX_TOKEN_ID') }}"
proxmox_token_secret: "{{ lookup('ansible.builtin.env', 'PROXMOX_TOKEN_SECRET') }}"
proxmox_node: "{{ lookup('ansible.builtin.env', 'TF_VAR_PROXMOX_NODE') }}"